
/gate/geometry/setMaterialDatabase    4hole/GateMaterials.db
#=====================================================
# GEOMETRY
#=====================================================

#/control/execute                         4hole/geometry.mac
#/control/execute                         4hole/bjhgeometry.mac
/gate/world/geometry/setXLength       800. mm
/gate/world/geometry/setYLength       800. mm
/gate/world/geometry/setZLength       800. mm

# SPECT Head: main volume, everything is included in SPECThead
# the name MUST be SPECThead
/gate/world/daughters/name SPECThead
/gate/world/daughters/insert box
/gate/SPECThead/geometry/setXLength 80 cm
/gate/SPECThead/geometry/setYLength 80 cm
/gate/SPECThead/geometry/setZLength 80 cm
/gate/SPECThead/vis/setColor white
/gate/SPECThead/setMaterial Air
/gate/SPECThead/vis/forceWireframe


#collimator
/gate/SPECThead/daughters/name barrier1
/gate/SPECThead/daughters/insert box
/gate/barrier1/geometry/setXLength  1 mm
/gate/barrier1/geometry/setYLength  30 mm
/gate/barrier1/geometry/setZLength  0.1 cm
/gate/barrier1/placement/setTranslation  105.5 35 0 mm
/gate/barrier1/setMaterial Tungsten
/gate/barrier1/vis/setColor yellow

/gate/SPECThead/daughters/name barrier2
/gate/SPECThead/daughters/insert box
/gate/barrier2/geometry/setXLength  1 mm
/gate/barrier2/geometry/setYLength  30 mm
/gate/barrier2/geometry/setZLength  0.1 cm
/gate/barrier2/placement/setTranslation  105.5 -35 0 mm
/gate/barrier2/setMaterial Tungsten
/gate/barrier2/vis/setColor yellow

/gate/SPECThead/daughters/name barrier3
/gate/SPECThead/daughters/insert box
/gate/barrier3/geometry/setXLength  1 mm
/gate/barrier3/geometry/setYLength  12 mm
/gate/barrier3/geometry/setZLength  0.1 cm
/gate/barrier3/placement/setTranslation  105.5 13 0 mm
/gate/barrier3/setMaterial Tungsten
/gate/barrier3/vis/setColor yellow

/gate/SPECThead/daughters/name barrier4
/gate/SPECThead/daughters/insert box
/gate/barrier4/geometry/setXLength  1 mm
/gate/barrier4/geometry/setYLength  12 mm
/gate/barrier4/geometry/setZLength  0.1 cm
/gate/barrier4/placement/setTranslation  105.5 -13 0 mm
/gate/barrier4/setMaterial Tungsten
/gate/barrier4/vis/setColor yellow

/gate/SPECThead/daughters/name barrier5
/gate/SPECThead/daughters/insert box
/gate/barrier5/geometry/setXLength  1 mm
/gate/barrier5/geometry/setYLength  12 mm
/gate/barrier5/geometry/setZLength  0.1 cm
/gate/barrier5/placement/setTranslation  105.5 0 0 mm
/gate/barrier5/setMaterial Tungsten
/gate/barrier5/vis/setColor yellow

# Shielding: crystal
/gate/SPECThead/daughters/name crystal1
/gate/SPECThead/daughters/insert box
/gate/crystal1/geometry/setXLength 0.3 cm
/gate/crystal1/geometry/setYLength 0.2 cm
/gate/crystal1/geometry/setZLength  0.1 cm
/gate/crystal1/placement/setTranslation  155.5 0 0 mm
/gate/crystal1/setMaterial NaI
/gate/crystal1/vis/setColor yellow
/gate/crystal1/repeaters/insert                   ring
/gate/crystal1/ring/setRepeatNumber                12

/gate/SPECThead/daughters/name crystal2
/gate/SPECThead/daughters/insert box
/gate/crystal2/geometry/setXLength 0.3 cm
/gate/crystal2/geometry/setYLength 0.2 cm
/gate/crystal2/geometry/setZLength  0.1 cm
/gate/crystal2/placement/setTranslation  155.5 3 0 mm
/gate/crystal2/setMaterial NaI
/gate/crystal2/vis/setColor yellow
/gate/crystal2/repeaters/insert                   ring
/gate/crystal2/ring/setRepeatNumber                12

/gate/SPECThead/daughters/name crystal3
/gate/SPECThead/daughters/insert box
/gate/crystal3/geometry/setXLength 0.3 cm
/gate/crystal3/geometry/setYLength 0.2 cm
/gate/crystal3/geometry/setZLength  0.1 cm
/gate/crystal3/placement/setTranslation  155.5 -3 0 mm
/gate/crystal3/setMaterial NaI
/gate/crystal3/vis/setColor yellow
/gate/crystal3/repeaters/insert                   ring
/gate/crystal3/ring/setRepeatNumber                12

#/gate/shielding/moves/insert         rotation
#/gate/shielding/rotation/setSpeed    0.06 deg/s
#/gate/shielding/rotation/setAxis     0 0 1
/gate/systems/SPECThead/crystal/attach crystal1
/gate/crystal1/attachCrystalSD
/gate/systems/SPECThead/crystal/attach crystal2
/gate/crystal2/attachCrystalSD
/gate/systems/SPECThead/crystal/attach crystal3
/gate/crystal3/attachCrystalSD

#=====================================================
# PHYSICS
#=====================================================

/gate/physics/addPhysicsList emstandard_opt3
/gate/physics/processList Enabled
/gate/physics/processList Initialized

#=====================================================
# INITIALISATION
#=====================================================


/gate/run/initialize

#=====================================================
# VISUALISATION
#=====================================================

/vis/open                     OGLIQt
/vis/drawVolume
/vis/viewer/flush
/tracking/storeTrajectory     1
/vis/scene/add/trajectories
/vis/scene/endOfEventAction   accumulate
#/vis/scene/add/axes            0 0 0 500 mm
#/vis/scene/add/text            10 0 0 cm  20 0 0   X
#/vis/scene/add/text            0 10 0 cm  20 0 0   Y
#/vis/scene/add/text            0 0 10 cm  20 0 0   Z
/vis/viewer/set/auxiliaryEdge  true
/vis/reviewKeptEvents
/vis/viewer/flush

#=====================================================
#   D I G I T I Z E R: DETECTOR ELECTRONIC RESPONSE
#===================================================== 
/gate/digitizerMgr/crystal1/SinglesDigitizer/Singles/insert adder
/gate/digitizerMgr/crystal2/SinglesDigitizer/Singles/insert adder
/gate/digitizerMgr/crystal3/SinglesDigitizer/Singles/insert adder
#=====================================================
#  P A R T I C L E   S O U R C E
#=====================================================

/control/execute                          4hole/source.mac


#=====================================================
#  D A T A   O U T P U T   
#=====================================================

/gate/output/root/enable
/gate/output/root/setFileName             4hole/4hole
/gate/output/root/setRootHitFlag         1
/gate/output/root/setRootSinglesFlag      1
#/gate/output/root/setRootCoincidencesFlag 0
#/gate/output/root/verbose 3



#=====================================================
#  R U N Parameters 
#=====================================================
/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto #123456789
/gate/random/verbose 1

/gate/application/setTimeSlice   1000 s # 2s
/gate/application/setTimeStart   0. s
/gate/application/setTimeStop     1000 s
/gate/application/startDAQ
